Неверное отображение некоторых контестов в kks top
darkkeks/kks pull request #135
Opened 2023-04-06 14:22 UTC by m0r0zk01

Контест с длинным именем и небольшим числом задач криво отображается в таблице

До:
<img width="126" alt="image" src="https://user-images.githubusercontent.com/47718803/230406177-76f4bb8e-9dd6-4fbb-9326-ab0ac8f0cee6.png">

После:
<img width="126" alt="image" src="https://user-images.githubusercontent.com/47718803/230406102-1d966c1f-1379-443b-8a5b-87a8fb8d33a8.png">

2023-04-06 21:20 UTC, vvd170501 requested changes

2023-04-06 21:20 UTC, vvd170501 commented on kks/cmd/top.py
> +                    '{:>3}'.format(task.table_score() or '') + ' ' * (max(0, len(contest) - self.contest_widths[contest]) if i == len(tasks) else 0),
```python
max(0, len(contest) - self.contest_widths[contest])
```
Лучше поменять `get_contest_widths`, чтобы там тоже учитывалась длина имени контеста.

2023-04-06 21:20 UTC, vvd170501 commented on kks/cmd/top.py
> +                    '{:>3}'.format(task.table_score() or '') + ' ' * (max(0, len(contest) - self.contest_widths[contest]) if i == len(tasks) else 0),
Контесты непустые, поэтому можно добавить эти пробелы после внутреннего join'а. И создавать список тогда не придётся)

Я бы вообще выделил эту часть в какой-нибудь метод `_format_contest`. 2 вложенных списочных выражения с join'ами достаточно сложно читать (и списки, кстати, можно заменить на генераторы)

2023-04-06 22:21 UTC, m0r0zk01 commented on kks/cmd/top.py
> +                    '{:>3}'.format(task.table_score() or '') + ' ' * (max(0, len(contest) - self.contest_widths[contest]) if i == len(tasks) else 0),
Из-за того, что при вызовах `click.style()` на лету генерируются стили, выходная строка забивается кучей ANSI-кодов и высчитать нужный паддинг после join становится не так просто, я вроде это решил, но не без танцев с бубном)

2023-04-06 22:55 UTC, vvd170501 commented on kks/cmd/top.py
> +                    '{:>3}'.format(task.table_score() or '') + ' ' * (max(0, len(contest) - self.contest_widths[contest]) if i == len(tasks) else 0),
ANSI-коды я не учёл (
Всё равно выглядит достаточно сложно. Может, возвращать из `get_contest_widths` реальную ширину и ширину паддинга для каждого контеста (в каких-нибудь namedtuple)?

2023-04-07 19:02 UTC, vvd170501 approved these changes

2023-04-07 19:09 UTC, vvd170501 commented on kks/cmd/top.py
> +        ) + ' ' * self.contests_properties[contest].score_padding
![Screenshot_20230407-220514~2](https://user-images.githubusercontent.com/36827317/230663795-05950510-f5af-4983-8e54-fac6a8de13b7.png)

Может, поставим паддинг слева? Сейчас выглядит как-то криво. Тем более, баллы в каждой задаче уже выравниваются по правому краю

2023-04-07 21:19 UTC, vvd170501 commented on kks/cmd/top.py
> +        ) + ' ' * self.contests_properties[contest].score_padding
Хотя, наверное, можно и так. Считаем, что колонка с баллами задачи всегда шириной в 3 символа, а сами колонки начинаются слева.
Если в таком контесте будет несколько задач, то выравнивание по левому краю, наоборот, выглядит более естественно

2023-04-07 21:19 UTC, merged

2023-04-07 21:21 UTC, m0r0zk01 commented on kks/cmd/top.py
> +        ) + ' ' * self.contests_properties[contest].score_padding
<img width="367" alt="image" src="https://user-images.githubusercontent.com/47718803/230680211-cf1be088-0252-4c40-a6b5-cb1a093fdc63.png">

Да, мне вот кажется, что с левым паддингом выглядит так, будто там есть какие-то нерешенные никем задачи(особенно, если еще немного удлинить имя контеста) :)