добавил атрибут --first_contest в my_score
darkkeks/kks pull request #136
Opened 2023-05-28 06:09 UTC by antyats

Работает для текущего 4 модуля

2023-05-29 21:11 UTC, vvd170501 requested changes

2023-05-29 21:11 UTC, vvd170501 commented on kks/cmd/my_score.py
> +@click.option('-f', '--first-contest', 'first_contest_', type=str,
Зачем подчеркивание в конце? Можно просто `first_contest`, а здесь имя переменной вообще не нужно будет явно указывать

2023-05-29 21:11 UTC, vvd170501 commented on kks/cmd/my_score.py
> +                if first_contest_:
`if first_contest is None or task.contest in contests`

2023-05-29 21:11 UTC, vvd170501 commented on kks/cmd/my_score.py
> +    return contests
Лучше `return set(contests)`, или сразу собирать множество вместо списка.

2023-05-30 07:33 UTC, vvd170501 requested changes

2023-05-30 07:33 UTC, vvd170501 commented on kks/cmd/my_score.py
> -
Здесь нужна пустая строка. Это разные категории импортов (стандартный модуль и внешний пакет)

2023-05-30 07:33 UTC, vvd170501 commented on kks/cmd/my_score.py
> +    raise ValueError("Couldn't find user in standings")
Всё-таки правильнее возвращать 0 (см. [обновленный комментарий](https://github.com/darkkeks/kks/pull/134#discussion_r1103641475))

2023-05-30 07:33 UTC, vvd170501 commented on kks/cmd/my_score.py
> +
Не хватает пустой строки

2023-05-30 08:18 UTC, vvd170501 commented on kks/cmd/my_score.py
> +        if not (contest.startswith('exam') or ((contest == 'kr04' or contest == 'ku04') and year == 2022)):
exam стоит перенести в `is_rated_contest`, чтобы экзамен пропускался даже без `--first-contest`

2023-05-30 10:21 UTC, antyats commented on kks/cmd/my_score.py
> +        if not (contest.startswith('exam') or ((contest == 'kr04' or contest == 'ku04') and year == 2022)):
так в is_rated_contest ищется sm, kr и ku, там же 'exam' вернет false, и он пропустится

2023-05-30 10:34 UTC, vvd170501 commented on kks/cmd/my_score.py
> +@click.option('-f', '--first_contest', type=str,
Лучше через дефис, а не подчеркивание

2023-05-30 14:53 UTC, vvd170501 approved these changes

2023-05-30 14:54 UTC, merged