Добавлена возможность запускать тесты без создания файлов
DarkKeks/kks pull request #21
Opened 2020-12-07 23:48 UTC by vvd170501

Добавлена опция --virtual для тестироваия без использования файлов.
Код генерации и проверки тестов перемещён в отдельный модуль.
Добавлен шаблон генератора (random инициализируется номером теста для возможности восстановления входных данных по номеру).
Добавлен номер теста при выводе WA/RE

2020-12-07 23:54 UTC, vvd170501 commented on kks/testing.py
> +    def _run_test(self, binary, test_number, in_, out, virtual, env):
Передача параметра virtual и использование 2 возможных типов для параметров in_ и out выглядит не очень. Пока не нашёл более подходящего решения

2020-12-08 18:48 UTC, DarkKeks requested changes

2020-12-08 18:48 UTC, DarkKeks commented on kks/cmd/test.py
> +    def __init__(self, *seqs):
А как оно работает без `super().__init__(*seqs)` ? :)

2020-12-08 18:48 UTC, DarkKeks commented on kks/cmd/test.py
> +@click.option('--virtual', is_flag=True,
`-v` ?

2020-12-08 18:48 UTC, DarkKeks commented on kks/cmd/test.py
> +        checker.run_virtual(binary, gen, chain_with_len(tests, test_range))  # assuming tests & test_range == {}, otherwise may run some tests twice
Почему не сделать `set(tests) + set(test_range)` ? (тогда и `chain_with_len` не нужен)
Или не хочется потенциально большой range генерировать?

2020-12-08 18:48 UTC, DarkKeks commented on kks/testing.py
> +    def _run_test(self, binary, test_number, in_, out, virtual, env):
Мне, честно говоря, лень думать :)
Если работает как надо, можно и так оставить
По возможности кто-нибудь порефакторит

2020-12-08 18:48 UTC, DarkKeks commented on kks/testing.py
> +    def _run_binary(self, binary, args, stdin=None, stdout=None, input=None):
Может быть статическим, или функцией вне класса
Возможно стоит даже в `util` унести

2020-12-08 18:48 UTC, DarkKeks commented on kks/testing.py
> +        return self._run_binary(self.solution, args, stdin=in_stream, stdout=out_stream)
А зачем вот эти два метода? Они же не делают ничего полезного))

2020-12-08 18:48 UTC, DarkKeks commented on kks/testing.py
> +            test_number = test if virtual else int(test.stem)
IIRC сейчас поддерживаются тесты с "не-чиселком" в названии
Не уверен стоит ли это ломать

Мне кажется норм выводить просто `.stem`
Ну или число если число, иначе `.stem`

2020-12-08 19:08 UTC, vvd170501 commented on kks/testing.py
> +                             'does not exist, skipping', fg='red', err=True)
В этом случае входной файл не найден - т.е. какие-то тесты (предположительно) должны генерироваться, но их нет. В других случаях тесты уже существуют, поэтому достаточно предупреждения.

2020-12-08 19:17 UTC, vvd170501 commented on kks/cmd/test.py
> +    def __init__(self, *seqs):
Инициализация chain происходит в методе __new__ (см. https://ru.stackoverflow.com/questions/1152242/)

2020-12-08 19:22 UTC, vvd170501 commented on kks/cmd/test.py
> +@click.option('--virtual', is_flag=True,
Не уверен, что стоит добавлять, т.к. обычно `-v` == `--verbose`

2020-12-08 19:26 UTC, vvd170501 commented on kks/cmd/test.py
> +        checker.run_virtual(binary, gen, chain_with_len(tests, test_range))  # assuming tests & test_range == {}, otherwise may run some tests twice
Выглядит хорошей идеей, т.к. больше 1e6 тестов невозможно прогнать за разумное время

2020-12-08 19:43 UTC, DarkKeks commented on kks/cmd/test.py
> +@click.option('--virtual', is_flag=True,
В любом случае хочется короткий вариант, печатать `--virtual` лениво))
Какое-нибудь `-vr` тоже норм

2020-12-08 19:47 UTC, vvd170501 commented on kks/cmd/test.py
> +        checker.run_virtual(binary, gen, chain_with_len(tests, test_range))  # assuming tests & test_range == {}, otherwise may run some tests twice
Сделано в 200ac52

2020-12-08 19:48 UTC, DarkKeks commented on kks/cmd/test.py
> +    def __init__(self, *seqs):
Жесть технологии

2020-12-08 19:49 UTC, vvd170501 commented on kks/cmd/test.py
> +    def __init__(self, *seqs):
UPD: Удалено в 200ac52

2020-12-08 19:51 UTC, vvd170501 commented on kks/cmd/test.py
> +@click.option('--virtual', is_flag=True,
Как вариант, `-vt`. По крайней мере, можно расшифровать как "virtual tests". `-vr` выглядит не слишком очевидно

2020-12-08 20:01 UTC, vvd170501 commented on kks/testing.py
> +            test_number = test if virtual else int(test.stem)
int используется для вывода номера при WA/RE.
Да, оказалось, что при этом ломаются нечисловые названия.
Еще одна причина использовать stem - генератор использует строку (=stem), а не число для `random.seed`

2020-12-08 20:05 UTC, vvd170501 commented on kks/testing.py
> +            test_number = test if virtual else int(test.stem)
Исправлено в b382fab

2020-12-08 20:09 UTC, vvd170501 commented on kks/testing.py
> +        return self._run_binary(self.solution, args, stdin=in_stream, stdout=out_stream)
`_gen_input` был добавлен, чтобы вызывать генератор с разными потоками вывода. `_gen_output` должен был работать так же, но тогда пришлось бы добавлять много лишних аргументов. Поэтому из `gen_output` вызывается `_run_binary` напрямую.

2020-12-08 20:10 UTC, vvd170501 commented on kks/testing.py
> +        return self._run_binary(self.solution, args, stdin=in_stream, stdout=out_stream)
Если замена этих методов на прямые вызовы `_run_binary` не ухудшит читаемость кода, могу убрать их

2020-12-08 20:23 UTC, vvd170501 commented on kks/testing.py
> +        return self._run_binary(self.solution, args, stdin=in_stream, stdout=out_stream)
Убрано в f66f63d

2020-12-08 20:23 UTC, vvd170501 commented on kks/testing.py
> +    def _run_binary(self, binary, args, stdin=None, stdout=None, input=None):
Сделано в f66f63d

2020-12-08 20:25 UTC, vvd170501 commented on kks/cmd/test.py
> +@click.option('--virtual', is_flag=True,
Добавлено в 98476ea

2020-12-08 20:57 UTC, DarkKeks approved these changes

2020-12-08 20:57 UTC, merged

2020-12-08 20:59 UTC, vvd170501 commented
Стоит обновить версию до 1.3.0