Добавлена возможность скрывать папки контестов
DarkKeks/kks pull request #25
Opened 2020-12-10 00:12 UTC by vvd170501

2020-12-10 21:42 UTC, vvd170501 commented
Есть проблема при использовании команды следующим образом: `kks hide *`
В таком случае все файлы перемещаются в скрытую папку, при этом их расширения удаляются. 
Возможный вариант исправления - при синхронизации сохранять куда-нибудь список существующих контестов, а при запуске `kks hide` искать каждый аргумент в этом списке.
Тогда возникает новый вопрос - что делать с аргументами, которые не являются названиями контестов - выводить предупреждение или просто игнорировать?

2020-12-10 22:43 UTC, vvd170501 commented on kks/cmd/hide.py
> +        click.secho(f'Inconsistent workspace, run "kks sync" to enable contest hiding', fg='yellow', err=True)
Насчёт этого решения не уверен. Это условие срабатывает, если синхронизация не проводилась или проводилась только через старую версию kks.
Альтернативный вариант - сделать для этого случая что-то подобное:
```
is_valid_contest = '/' not in contest and re.match(r'[a-z]{2}\d{2}$', contest) and contest_dir.is_dir()
```
Но тогда код усложняется и появляется вероятность некорректной классификации имени директории

2020-12-11 07:35 UTC, DarkKeks commented
Сорян, не нашел пока времени вникнуть

Вижу что добавляешь индекс с контестами
Хочешь чтобы hide/unhide работал только с настоящими контестами, а не с произвольными папками/файлами?

Мне кажется наоброт, норм было бы прятать любые файлы/папки на 1-м/2-м уровне от корня
А что уже пользователь в них хранит &mdash; его дело?
Даже не факт что хочется ограничивать расстоянием от корня; возможно было бы удобно прятать части решения

----

Расскажи какие видишь в этом проблемы :)

2020-12-11 13:53 UTC, vvd170501 commented
Насчёт удаления расширений - старая версия сохраняла только stem (предполагалось, что команда будет использоваться только с именами директорий).
***
Если добавить возможность скрывать произвольные файлы, то возникает следующая проблема:
При вызове `kks hide *` скроются все файлы/директории, при этом нельзя сделать `kks unhide *`, чтобы вернуть их обратно - придётся перечислять имена ошибочно скрытых файлов в аргументах или перемещать их обратно вручную.
Аналогично, пользователь может вызвать `kks hide sm*` (предполагая, что скроются только папки, соответствующие семинарским контестам), при этом, если в корневой директории существовал (например) файл sm03-1.c, он тоже скроется

2020-12-11 13:57 UTC, vvd170501 commented
Насчёт возможности скрывать директории отдельных задач - не уверен, насколько это целесообразно. В каждом контесте не так много задач, при этом, если контест скрыт не полностью, он все равно будет виден в корневой директории.

2020-12-11 14:22 UTC, vvd170501 commented
Почистил историю коммитов, перенес не связанные с новым кодом исправления стиля в #26

2020-12-11 15:00 UTC, DarkKeks requested changes
Падает sync
Остальное на твое усмотрение)

2020-12-11 15:00 UTC, DarkKeks commented on kks/cmd/hide.py
> +                contest_dir.rename(hidden_dir / contest_dir.stem)
Все еще не вижу смысла здесь брать `.stem`

2020-12-11 15:00 UTC, DarkKeks commented on kks/cmd/init.py
> +    hidden = get_hidden_dir([path])
Почему список?

2020-12-11 15:00 UTC, DarkKeks commented on kks/util.py
> +def get_contest_dir(workspace, contest):
Возможно стоит приоретизировать "не спрятанную" папку?
Или как то падать/писать варнинг если есть обе?

2020-12-11 15:00 UTC, DarkKeks commented on kks/cmd/hide.py
> +            click.secho(f'Contest {contest} does not exist (or wasnt synced)', fg='yellow', err=True)
Получается в случае `kks hide *` будем ругаться на каждый файл?
А есть ли смысл?

2020-12-11 15:00 UTC, DarkKeks commented on kks/util.py
> +    index_file = get_hidden_dir(workspace) / '.index'
Падает при отсутствии папки (`kks sync` после этого коммита, например)

2020-12-11 15:01 UTC, DarkKeks commented
А какие юзкейсы для хранения "произвольных" файлов рядом с папками контестов?

Мне просто очень не хочется
- гвоздями прибивать список контестов из ejudge к списку папок (прямо сейчас единственное, что не будет полноценно работать при "нестандартной структуре папок" &mdash; это sync и, возможно, submit)
  При этом могу представить, что кому-то удобнее использовать папки вида `sm01-5`. И чтобы их полноценно поддерживать достаточно было бы научить sync так создавать папки
  Или просто если хочется отдельные папки не привязанные к задачам, но тоже хочется уметь с ними работать
- Ломать привычное "везде где работает * из баша используются файлы"
  Вернуть контесты обратно через * же тоже не получится &mdash; получается какая то ассиметрия

Если хочется вернуть все файлы, спрятанные случайно, никто ведь не мешает сделать `kks unhide .hidden/*`
Может было бы для сценария "спрятать всё" иметь какое нибудь `-a`..

----
Впрочем, мне особо без разницы, все километры текста выше врядли имеют значение для реального использования :)

Если хочешь оставить так &mdash; говори, замержу)

2020-12-11 15:03 UTC, vvd170501 commented on kks/util.py
> +def get_contest_dir(workspace, contest):
В текущей реализации папка должна существовать только в одном экземпляре (только если пользователь не создал папку с таким же именем вручную)

2020-12-11 15:04 UTC, vvd170501 commented on kks/util.py
> +def get_contest_dir(workspace, contest):
Насчёт приоритетов - по умолчанию папка создаётся не скрытой

2020-12-11 15:08 UTC, DarkKeks commented on kks/util.py
> +def get_contest_dir(workspace, contest):
В любом случае пока папка контеста не используется нигде кроме sync, так что пофиг
:+1:

2020-12-11 15:23 UTC, vvd170501 commented
> А какие юзкейсы для хранения "произвольных" файлов рядом с папками контестов?

Например, если `kks init` был запущен в уже не пустой директории

>   При этом могу представить, что кому-то удобнее использовать папки вида `sm01-5`. И чтобы их полноценно поддерживать достаточно было бы научить sync так создавать папки

В таком случае усложняется возможная структура директорий (например, часть контестов может оказаться синхронизирована в папки вида `smxx/yy`, а часть - в виде `smxx-yy`

Тогда придётся усложнять поиск директорий для задач при синхронизации, также может сломаться автоопределение задачи в submit

> Если хочется вернуть все файлы, спрятанные случайно, никто ведь не мешает сделать `kks unhide .hidden/*`

В таком случае появляется неопределенность:: `unhide sm01` и `unhide .hidden/sm01` должны понимать, что имеется в виду одна и та же директория

Отсюда же ещё одна проблема: если вызвать `kks hide .hidden`, вообще неизвестно, что должно произойти (хотя можно объявить это UB и считать, что так никто делать не будет)

> Может было бы для сценария "спрятать всё" иметь какое нибудь `-a`

Хорошая идея, добавлю

> Или выбирать контесты через опции. А аргументами позволять выбирать только файлы. Или совсем аргументы убрать

Если указывать через опции, то (если я правильно понимаю), перед каждым названием придётся писать имя самой опции, и это менее удобно, чем аргументы

2020-12-11 15:24 UTC, vvd170501 commented on kks/cmd/hide.py
> +            click.secho(f'Contest {contest} does not exist (or wasnt synced)', fg='yellow', err=True)
Какие есть альтернативы? Просто игнорировать?

2020-12-11 15:27 UTC, vvd170501 commented on kks/cmd/init.py
> +    hidden = get_hidden_dir([path])
Похоже на опечатку

2020-12-11 15:38 UTC, DarkKeks commented on kks/cmd/hide.py
> +            click.secho(f'Contest {contest} does not exist (or wasnt synced)', fg='yellow', err=True)
Сойдет

2020-12-11 15:55 UTC, vvd170501 commented
Есть ещё одна проблема - при повторной синхронизации выводится полный путь к скрытым папкам (см. скриншот)
![Screenshot_20201211-185208~2](https://user-images.githubusercontent.com/36827317/101924728-0f48a980-3be2-11eb-80bb-11657e4a7506.png)
Есть 2 варианта решения:
* Не выводить предупреждения для скрытых папок
* Выводить путь относительно `.kks-contests`
Какой вариант лучше, или, может быть, есть ещё какие-нибудь альтернативы?

2020-12-11 15:58 UTC, vvd170501 commented on kks/cmd/hide.py
> +                contest_dir.rename(hidden_dir / contest_dir.stem)
Заменил на `.name`

2020-12-11 15:58 UTC, vvd170501 commented on kks/cmd/init.py
> +    hidden = get_hidden_dir([path])
Исправлено

2020-12-11 15:58 UTC, vvd170501 commented on kks/util.py
> +    index_file = get_hidden_dir(workspace) / '.index'
Исправлено

2020-12-11 16:01 UTC, DarkKeks commented
Может совсем варнинги убрать? Или придумать что-то вместо них
Количество задач растет, количество варнингов вместе с ними
Писать такую стену текста каджый раз мало смысла))

2020-12-11 16:04 UTC, vvd170501 commented
Возможно, если все задачи контеста уже были синхронизированы, можно выводить одно сообщение на весь контест. Но это уже лучше реализовывать в отдельной ветке.

2020-12-11 16:18 UTC, vvd170501 commented on kks/cmd/hide.py
> +        contests = valid_contests
Да, в таком случае упадёт. Добавлю проверку

2020-12-11 16:20 UTC, vvd170501 commented on kks/cmd/hide.py
> +        contests = valid_contests
Причем падает не только в случае с all, но и при попытке скрыть любой удаленный после синхронизации контест

2020-12-11 16:25 UTC, vvd170501 commented on kks/cmd/hide.py
> +        contests = valid_contests
Исправлено

2020-12-11 16:30 UTC, DarkKeks commented
Можно же мержить уже дааа?

2020-12-11 16:31 UTC, DarkKeks commented
Давай я тебе контрибьютора дам уже))

2020-12-11 16:32 UTC, DarkKeks commented
По ссылке можно принять инвайт: https://github.com/DarkKeks/kks/invitations

2020-12-11 16:36 UTC, vvd170501 commented
Да, текущую версию можно мержить

2020-12-11 16:38 UTC, merged