Частичная поддержка API ejudge, улучшение команды submit
DarkKeks/kks pull request #58
Opened 2021-02-04 19:13 UTC by vvd170501

Добавлен класс для работы с API, поддерживается б*о*льшая часть методов, используемых в ejudge-fuse (возможное решение для загрузки условий КР? (#55))
Улучшена команда `kks submit` - скрипт выводит результат тестирования, если оно успевает завершиться за ~10 с.

2021-02-04 20:13 UTC, LoDThe commented
Ну что, успеешь ревью до начала кр сделать, @DarkKeks? :clown_face:

2021-02-04 20:17 UTC, ruct commented
> Ну что, успеешь ревью до начала кр сделать, @DarkKeks?

Лучше бы шаринг решений до кр сделали :cry:

2021-02-05 08:49 UTC, vvd170501 commented
Похоже, доступ к КР все-таки ограничивается по IP, поэтому скачивание условий / отправка решений так и не будут работать.

2021-02-05 10:38 UTC, vvd170501 commented on kks/util/ejudge.py
> +        """get new sids"""
Этот метод пока не используется, но может пригодиться, если класс API будет использоваться отдельно от сессии

2021-02-05 10:40 UTC, vvd170501 commented on kks/util/ejudge.py
> +        self._api_auth_data = API.AuthData(None, None)
Используется для обновления (EJ)SID в созданных объектах API при обновлении куков

2021-02-06 10:18 UTC, MarshalX requested changes

2021-02-06 10:18 UTC, MarshalX commented on kks/ejudge_submit.py
> +        return False, 'Invalid problem ID'
Слишком плохая привычка так поступать. Хватит возвращать кортежи из каких-то разнородных данных и потом ещё ужасно с ними работать

2021-02-06 10:18 UTC, MarshalX commented on kks/ejudge_submit.py
> +        'is_pending' in problem_status or
Есть замечательная штука, которая называется any()

2021-02-06 10:18 UTC, MarshalX commented on kks/errors.py
> +        self.err = err
Давай готовить ошибки по мере их получения после запроса и потом скармливать какому-то конструктору собранные данные, а не по мере создания экземпляра ошибки что-то тут парсить

2021-02-06 10:18 UTC, MarshalX commented on kks/ejudge_submit.py
> +        sleep_dt = max(0, t_start + dt - time())
Задержка не должна быть константой, а должна увеличиваться. Ретраи вообще должны быть в логике, которая занимается отправкой и обработкой запроса, а не тут

2021-02-06 10:18 UTC, MarshalX commented on kks/ejudge_submit.py
> +    langs = [e for e in all_langs if e['id'] in available]
Мы в python не используем тут e. У нас i (item). А по возможности называем более нормально Аля lang(l)

2021-02-06 11:46 UTC, vvd170501 commented on kks/util/ejudge.py
> +                raise APIError('Invalid response. resp={resp.content}, err={e}')
Исправил

2021-02-06 11:46 UTC, vvd170501 commented on kks/errors.py
> +        self.err = err
Переписал в 110e77d

2021-02-06 11:49 UTC, vvd170501 commented on kks/ejudge_submit.py
> +        choices = ['{} - {}'.format(e['short_name'], e['long_name']) for e in langs]
f-strings, но в них нельзя использовать кавычки

2021-02-06 11:58 UTC, vvd170501 commented on kks/__version__.py
> +__version__ = '1.10.0-b1'
Перенёс. Не знал, что в  setup.py можно импортировать пакет

2021-02-06 12:02 UTC, vvd170501 commented on kks/util/ejudge.py
> +        url = self._prefix + path
Чем такой вариант будет лучше? Префикс все равно общий для всех запросов

2021-02-06 12:46 UTC, MarshalX commented on kks/util/ejudge.py
> +        url = self._prefix + path
Если в двух словах, то этой логике тут не место. Выглядит как лютый хардкод. Твоя _request обёртка над _http.чтоТоТам с доп обработкой авторизации, ошибок, ответов и прочей хурмы должна +- повторять аргументы того, что оборачиваешь, с доп свистелками типа флажков, но построение урла для запроса сюда не входит. Хочешь где-то билдить урл не в методах - сделай билдер между методом АПИ и твоим _request()

2021-02-06 12:49 UTC, vvd170501 commented on kks/util/ejudge.py
> +        return self._request('client', 'problem-statement-json', data=data, decode=False)
Переписал в ccab7b0. Методы, возвращающие чистые данные все равно выдают ошибки в json, поэтому пробовать декодировать ответ нужно для всех методов

2021-02-06 12:52 UTC, vvd170501 commented on kks/util/ejudge.py
> +        url = self._prefix + path
Переписал в ccab7b0. Построение аргументов запроса и сам запрос теперь в отдельных функциях

2021-02-06 13:03 UTC, vvd170501 commented on kks/util/ejudge.py
> +            'run_id': int(run_id)
Предполагалось, что в методы может передаваться как число, так и строка. Пока используются только числа

2021-02-06 13:42 UTC, vvd170501 commented on kks/util/ejudge.py
> +        auth_data = self._request('register', 'enter-contest-json', (auth_data['EJSID'], auth_data['SID']), data=data)
Насчёт разделения - первый запрос сам по себе бесполезен, т.к. возвращает EJSID/SID, которые могут использоваться только для `enter-contest-json`.
При этом значения (EJ)SID, полученные в результате `login-json`, устареют одновременно с (EJ)SID, полученными от `enter-contest-json`, т.е. не смогут использоваться для обновления устаревших EJSID/SID контеста

2021-02-06 13:47 UTC, MarshalX commented on kks/ejudge_submit.py
> +        choices = ['{} - {}'.format(e['short_name'], e['long_name']) for e in langs]
Можно. Даже два способа имеется. Первый экранирование кавычек, второй использовать двойные как основные, если внутри одинарные.

2021-02-06 13:51 UTC, MarshalX commented on kks/util/ejudge.py
> +        auth_data = self._request('register', 'enter-contest-json', (auth_data['EJSID'], auth_data['SID']), data=data)
Я чета не догнал что мы тут делаем. Кажется обертку над апи. Тогда откуда у нас взялись какие-то объединённые методы? 1 ручка - 1 метод. Что-то вспомогательное типа авторизации, которая использует два метода, можешь где-то написать. Пусть будет даже в твоём классе апи. Ибо ну уж слишком много переписать надо будет в противном случае

2021-02-06 13:52 UTC, vvd170501 commented on kks/ejudge_submit.py
> +        choices = ['{} - {}'.format(e['short_name'], e['long_name']) for e in langs]
С экранированием выдаёт SyntaxError:
```
>>> foo = {'a': 1}
>>> f'{foo[\'a\']}
SyntaxError: f-string expression part cannot include a backslash
```

С двойными кавычками действительно работает, не знал об этом

2021-02-06 13:54 UTC, MarshalX commented on kks/util/ejudge.py
> +            'run_id': int(run_id)
Окей. А придумаешь что-нибудь лучше чем каждый раз пересоздавать словарь, когда там одно поле и его имя совпадает с названием аргумента?

2021-02-06 14:10 UTC, vvd170501 commented on kks/ejudge_submit.py
> +        sleep_dt = max(0, t_start + dt - time())
Насчёт времени задержки - увеличение интервала имеет смысл при долгом ожидании ответа (например, проблемы с соединением). Здесь предполагается, что ответ от api приходит достаточно быстро.
Если тестирование идёт достаточно долго, то (скорее всего) решение получает TL на большом числе тестов, и неизвестно, сколько ещё нужно ждать результата. В таком случае просто возвращается `Testing in progress`

2021-02-06 14:13 UTC, vvd170501 commented on kks/ejudge_submit.py
> +        sleep_dt = max(0, t_start + dt - time())
Насчёт логики запроса - в классе API есть методы `submit` и `run_status`, которые только отправляюют запрос и возвращают результат. Ретраи в методах api в принципе не предусмотрены. Создавать какую-нибудь отдельную функцию `final_run_status` не вижу смысла, т.к. она нужна только для получения статуса только что отправленой посылки

2021-02-06 14:20 UTC, MarshalX commented on kks/ejudge_submit.py
> +        sleep_dt = max(0, t_start + dt - time())
Противоречишь сам себе. Говоришь про обрыв соединения, а потом про быстрый ответ от апи. Какой ответ, когда инета нет. Профитнее и правильнее увеличивать задержку с каждой лажей. Почитай статью на хабре про то, как какой-то сервис сам себя задудосил из-за ошибки в коде, связанным с увеличением ожидания. Хотя может там просто количество попыток не лимитировано было. Короче почитай. Хуже не будет. Статье может неделя-две

2021-02-06 14:24 UTC, MarshalX commented on kks/ejudge_submit.py
> +        sleep_dt = max(0, t_start + dt - time())
https://habr.com/ru/company/vdsina/blog/539330/

2021-02-06 14:26 UTC, DarkKeks commented on kks/ejudge_submit.py
> +        sleep_dt = max(0, t_start + dt - time())
> Насчёт времени задержки - увеличение интервала имеет смысл при долгом ожидании ответа (например, проблемы с соединением). Здесь предполагается, что ответ от api приходит достаточно быстро.
> Если тестирование идёт достаточно долго, то (скорее всего) решение получает TL на большом числе тестов, и неизвестно, сколько ещё нужно ждать результата. В таком случае просто возвращается `Testing in progress`

Ну да, в этом же и смысл возрастающей задержки между запросами
Если решение протестилось быстро, то ты быстро получишь ответ
А если ты, скажем, 5 секунд подряд получаешь ответ, что решение тестируется, то значит оно потенциально будет тестироваться долго, поэтому делать запросы раз в 500мс смысла нету, можно подождать подольше

2021-02-06 14:28 UTC, vvd170501 commented on kks/util/ejudge.py
> +        auth_data = self._request('register', 'enter-contest-json', (auth_data['EJSID'], auth_data['SID']), data=data)
Не было цели написать полноценную обёртку. Были добавлены только методы, которые могут использоваться в kks. Некоторые методы (`user-contests-json`, `run-test-json`), скорее всего, никогда не понадобятся, поэтому не были реализованы. `login-json` и `enter-contest-json` вряд ли будут использоваться по отдельности, поэтому для них нет отдельных методов класса

2021-02-06 14:52 UTC, MarshalX commented on kks/util/ejudge.py
> +        auth_data = self._request('register', 'enter-contest-json', (auth_data['EJSID'], auth_data['SID']), data=data)
Но ты же сам их используешь. Ты можешь унифицировать код?

2021-02-06 15:11 UTC, vvd170501 commented on kks/util/ejudge.py
> +            'run_id': int(run_id)
Пока не могу придумать нормальный вариант реализации. максимум, что получилось - что-то такое:
```
from functools import wraps

def params(*names):
    def decorator(func):
        @wraps(func)
        def wrapper(self, *values):
            return func(self, **dict(zip(names, values)))
        return wrapper
    return decorator


class API:
    def _api_method(self, path, action, auth_data=None, need_json=True, **kwargs):
        print(path, action, kwargs.get('data', 'No data'))

    @params('problem', 'foo')
    def problem_status(self, **kwargs):
        return self._api_method('client', 'problem-status-json', data=kwargs)

a=API()
a.problem_status(123)
a.problem_status(123, 456)
a.problem_status(123, 456, 789)

>>> help(a.problem.status)
problem_status(**kwargs) method of foo.API instance
```
- По идее, только второй вызов метода должен быть корректным
- В описании метода не сохраняется информация о параметрах

2021-02-06 15:20 UTC, vvd170501 commented on kks/ejudge_submit.py
> +        sleep_dt = max(0, t_start + dt - time())
> Говоришь про обрыв соединения, а потом про быстрый ответ от апи

Я привёл пример, где увеличение задержки как раз было бы уместно. В данном случае проблемы с соединением вообще не рассматриваются, т.к. предполагается, что если удалось отправить решение, то и с получением статуса не возникнет проблем.

2021-02-06 15:52 UTC, vvd170501 commented on kks/util/ejudge.py
> +        self._api_auth_data = API.AuthData(None, None)
Переписал. EJSID все равно дублируется (в `self.http.cookies` и `self._sids`), но выглядит уже лучше

2021-02-06 15:59 UTC, vvd170501 commented on kks/util/ejudge.py
> +            data['EJSID'], data['SID'] = auth_data.ejsid, auth_data.sid
Переписал, теперь используется просто словарь.

2021-02-06 16:03 UTC, vvd170501 commented on kks/util/ejudge.py
> +            data['EJSID'], data['SID'] = auth_data.ejsid, auth_data.sid
Насчёт "добавить в запрос авторизацию" - `_api_method` как раз её добавляет

2021-02-06 16:56 UTC, vvd170501 commented on kks/ejudge_submit.py
> +    return False, 'Partial solution'
Исправил

2021-02-06 17:21 UTC, vvd170501 commented on kks/ejudge_submit.py
> +        sleep_dt = max(0, t_start + dt - time())
Добавил

2021-02-06 18:38 UTC, MarshalX requested changes

2021-02-06 18:38 UTC, MarshalX commented on kks/ejudge_submit.py
> +        return 'green' if self.status == self.OK else\
Такое мы в путоне пишем через словари и потом гетаем с дефолт параметром

2021-02-06 18:38 UTC, MarshalX commented on kks/ejudge_submit.py
> +    CHECK = 1
Выглядит как enum.Enum

2021-02-06 18:52 UTC, vvd170501 commented on kks/ejudge_submit.py
> +    CHECK = 1
В чём плюсы использования Enum в этом случае? Как тогда передавать сообщение в вызывающую функцию?

2021-02-06 18:52 UTC, MarshalX requested changes

2021-02-06 18:52 UTC, MarshalX commented on kks/ejudge_submit.py
> +            return SubmissionResult.parse_status(res)
Почему парс статуса принимает весь результат, а проверка что ещё тестируется только сам статус?

2021-02-06 18:52 UTC, MarshalX commented on kks/ejudge_submit.py
> +        if dt:
А от sleep(0) поплохеет?

2021-02-06 18:52 UTC, MarshalX commented on kks/ejudge_submit.py
> +    delays = [(3, 0.5), (6, 1), (10, 2)]
Давай не будем хардкодить непонятно в каком месте используя то, что без комментария не понять вообще и придумаем какую-нибудь формулку. А можно просто умножать на коеф каждую Н попыток

2021-02-06 18:52 UTC, MarshalX commented on kks/ejudge_submit.py
> +    delays = [(3, 0.5), (6, 1), (10, 2)]
Ограничить максимальное время ожидания ты всегда можешь. Как и суммарное

2021-02-06 18:54 UTC, DarkKeks commented on kks/ejudge_submit.py
> +            sleep(dt)
Чет сложновато :(

Я бы как-нибудь вот так написал наверное

```py
from time import time, sleep

s = time()

def api_call():
    current = time() - s
    print(f"Calling api at {current}")
    sleep(0.3)
    return None if current < 15 else 'Response'

def with_retries(func, delay=0.5, multiplier=1.5, timeout=10):
    overall_start = time()
    while True:
        start = time()
        result = func()
        if result is not None:
            return result
        elapsed = time() - start

        if time() - overall_start > timeout:
            return None

        sleep(max(0, delay - elapsed))
        delay *= multiplier

print(with_retries(api_call))
```

2021-02-06 18:57 UTC, MarshalX commented on kks/ejudge_submit.py
> +    CHECK = 1
Пища для размышлений, а не упрёк какой-то или призыв к переделывание

2021-02-06 18:59 UTC, vvd170501 commented on kks/ejudge_submit.py
> +    CHECK = 1
Если вынести только константы (OK/FAIL/etc.) в отдельный Enum, код будет выглядеть менее читаемо (пример ниже)
```
class SubmissionResult(Enum):
    OK = 1
    # ...

class SubmissionResultWithMessage:
    def __init__(...):
        # ...

    @classmethod
    def fail(cls, message):
        return SubmissionResultWithMessage(SubmissionResult.FAIL, message)
```

Или возможно как-то создать подкласс Enum, который позволяет создавать объекты с дополнительными параметрами?

2021-02-06 19:02 UTC, vvd170501 commented on kks/ejudge_submit.py
> +    CHECK = 1
Ок, понял. Простто пока это выглядит наиболее читаемым вариантом

2021-02-06 19:10 UTC, MarshalX commented on kks/ejudge_submit.py
> +            sleep(dt)
> Чет сложновато :(


```python
from time import time, sleep

s = time()

def api_call(url):
    current = time() - s
    print(f"Calling api ({url}) at {current}")
    sleep(0.3)
    return None if current < 15 else 'Response'

def with_retries(func, delay=0.5, multiplier=1.5, timeout=10):
    def wrapper(*args, **kwargs):
        nonlocal delay
        overall_start = time()
        while True:
            start = time()
            result = func(*args, **kwargs)
            if result is not None:
                return result
            elapsed = time() - start
    
            if time() - overall_start > timeout:
                return None
    
            sleep(max(0, delay - elapsed))
            delay *= multiplier
            
    return wrapper

print(with_retries(api_call)('https://jopa.kek/'))
```

Ну, как минимум, так, потому что ты убил возможность передать что-то внутрь api_call. Но меня смущает nonlocal)

2021-02-06 19:15 UTC, vvd170501 commented on kks/ejudge_submit.py
> +            sleep(dt)
Пока не совсем понятна логика `api_call` в примере. Зачем возвращать None, если результат успешно получен?

2021-02-06 19:23 UTC, MarshalX commented on kks/ejudge_submit.py
> +            sleep(dt)
```python
from time import time, sleep

def with_retries(func, delay=0.5, multiplier=1.5, timeout=10):
    def wrapper(*args, **kwargs):
        nonlocal delay
        overall_start = time()
        while True:
            start = time()
            result = func(*args, **kwargs)
            if result is not None:
                return result
            elapsed = time() - start
    
            if time() - overall_start > timeout:
                return None
    
            sleep(max(0, delay - elapsed))
            delay *= multiplier
            
    return wrapper

s = time()

@with_retries
def api_call(url):
    current = time() - s
    print(f"Calling api ({url}) at {current}")
    sleep(0.3)
    return None if current < 15 else 'Response'

print(api_call('https://jopa.kek/'))
```

UPD. с использованием @. Мало ли кто декоратор не признал и его несколько вариантов использования

2021-02-06 19:45 UTC, vvd170501 commented on kks/ejudge_submit.py
> +            sleep(dt)
Добавил

2021-02-06 19:55 UTC, vvd170501 commented on kks/ejudge_submit.py
> +            return SubmissionResult.parse_status(res)
Чтобы проверить, тестируется ли ещё решение, достаточно одного статуса (RunStatus - еще один класс типа `Enum`а)
Про парс статуса - просто изначально так написал (если не ошибаюсь, это было еще в первой версии парсера (is_ok)).
В статусе ещё передаются результаты тестов, поэтому есть смысл дописать парсер, чтобы он выдавал номера и статусы упавших тестов для частичных решений

2021-02-06 20:03 UTC, MarshalX commented on kks/util/common.py
> +    def decorator(func):
Зачем?

2021-02-06 20:07 UTC, vvd170501 commented on kks/util/common.py
> +    def decorator(func):
```
def with_retries(func, delay=0.5, multiplier=1.5, timeout=10):
    def wrapper(*args, **kwargs):
        ...
```
Как в таком варианте можно передать в декоратор кастомные аргументы?

2021-02-06 20:25 UTC, MarshalX commented on kks/util/common.py
> +    def decorator(func):
Понял, спасиб за ответ

2021-02-06 21:04 UTC, vvd170501 commented on kks/ejudge_submit.py
> +            return SubmissionResult.parse_status(res)
Добавлено

2021-02-06 23:20 UTC, MarshalX requested changes

2021-02-06 23:20 UTC, MarshalX commented on kks/util/ejudge.py
> +    @classmethod
Не класс, а статик

2021-02-06 23:20 UTC, MarshalX commented on kks/util/ejudge.py
> +        if 'testing_report' in run_status:
and тралала[´tests и можно без всяких .get() с ещё одним пустым листом. Работает за счёт того, что не у каждого операнда вычисляется значение. Как && в других языках

2021-02-06 23:20 UTC, MarshalX commented on kks/util/ejudge.py
> +            test_results = '\n'.join(map(test_descr, filter(lambda test: test['status'] not in [self.OK, self.SKIPPED], self.tests)))
Путонисты хейтят фильтр за нечитабельность. Особенно с лямбдами. Юзаем списковое включение

2021-02-06 23:20 UTC, MarshalX commented on kks/util/ejudge.py
> +            raise APIError(f'Invalid response. resp={resp.content}, err={e}', -1)
Откуда ты эти кода ошибок берёшь? Почему не код ответа апи, например?

2021-02-06 23:20 UTC, MarshalX commented on kks/util/ejudge.py
> +            raise APIError(err.get('message', 'Unknown error'), err.get('num', -1))
Странно видеть уверенность в наличии error, но опциональности message в error)

2021-02-06 23:20 UTC, MarshalX commented on kks/util/ejudge.py
> +    def list_runs(self, prob_id):
Забыл дефолт значения у арга? None

2021-02-06 23:20 UTC, MarshalX commented on kks/util/ejudge.py
> +        if prob_id is not None:
Реверси логику. С отрицанием сложнее читать

2021-02-06 23:29 UTC, vvd170501 commented on kks/util/ejudge.py
> +    @classmethod
Тогда придётся хардкодить имя класса для доступа к `_descriptions`

2021-02-06 23:31 UTC, vvd170501 commented on kks/ejudge_submit.py
> +        try:
Пока не совсем понимаю, как это должно выглядеть.
В текущем варианте реализации предполагается, что после успешной авторизации не будет новых ошибок

2021-02-06 23:37 UTC, vvd170501 commented on kks/util/ejudge.py
> +        if 'testing_report' in run_status:
Предлагается такой вариант:
```
if 'testing_report' in run_status and 'tests' in ...:
    self.tests = run_status['testing_report']['tests']
```
Или я что-то не так понял?

2021-02-06 23:44 UTC, vvd170501 commented on kks/util/ejudge.py
> +    def list_runs(self, prob_id):
Считал, что лучше всегда явно передавать аргумент. Да, с None по умолчанию выглядит лучше

2021-02-06 23:49 UTC, vvd170501 commented on kks/util/ejudge.py
> +            raise APIError(f'Invalid response. resp={resp.content}, err={e}', -1)
Код `-1` - не получилось декодировать ответ (т.е. не обязательно ошибка, связанная с API).

2021-02-06 23:53 UTC, vvd170501 commented on kks/util/ejudge.py
> +            raise APIError(err.get('message', 'Unknown error'), err.get('num', -1))
Переписал на `get`. У API ejudge нет документации (по крайней мере, в открытом доступе), поэтому сложно сказать, какие поля будут гарантированно присутствовать

2021-02-06 23:55 UTC, MarshalX commented on kks/util/ejudge.py
> +    @classmethod
Когда поле статическое, то обращаться к классовому полю через имя класса не хардкод. Если уж на то пошла речь, то раз классовый метод, то возвращать должен экземпляр )

2021-02-06 23:56 UTC, MarshalX commented on kks/util/ejudge.py
> +        if 'testing_report' in run_status:
Да +- такой

2021-02-06 23:59 UTC, MarshalX commented on kks/util/ejudge.py
> +            raise APIError(f'Invalid response. resp={resp.content}, err={e}', -1)
Тогда магическое значение или какое там правильное название для такого. Выноси куда-нибудь в константу

2021-02-06 23:59 UTC, vvd170501 commented on kks/util/ejudge.py
> +        if 'testing_report' in run_status:
Чем это лучше старого варианта? Условие длиннее (читать сложнее?), результат тот же

2021-02-07 00:02 UTC, MarshalX commented on kks/util/ejudge.py
> +            raise APIError(err.get('message', 'Unknown error'), err.get('num', -1))
Раз нет доки я бы вообще нигде не верил и учитывал то, что поля может и не быть. Ну это так. По опыту личному

2021-02-07 00:04 UTC, vvd170501 commented on kks/util/ejudge.py
> +            raise APIError(f'Invalid response. resp={resp.content}, err={e}', -1)
Добавил. Коды для отсутствующего кода ошибки/поля error и ошибки чтения сделал разными (всё-таки это не одно и то же)

2021-02-07 00:05 UTC, MarshalX commented on kks/util/ejudge.py
> +        if 'testing_report' in run_status:
Тем, что ты так с помощью одного приходишь к решению. С помощью условия в ифе. Так не надо понимать условие и ещё логику с .гет когда кто-то будет читать код. Увидит в начале дефолт лист, потом условие по которому этот лист может обновиться и ок. Что конкретно за условие его может вообще не волновать. А когда ты налепишь и иф, и чёта ещё внутри, то сиди читай все и думай что тут происходит

2021-02-07 00:07 UTC, vvd170501 commented on kks/util/ejudge.py
> +            raise APIError(err.get('message', 'Unknown error'), err.get('num', -1))
Некоторые поля (типа ok и response (при ok=true)) считаются всегда существующими. Если это не так, то с таким ответом в принципе нет смысла что-то делать.

2021-02-07 00:13 UTC, vvd170501 commented on kks/ejudge_submit.py
> +        try:
Как вариант - написать что-то такое:
```
try:
    contest = session.with_auth(api.contest_status)
except AuthError:
    ...
except APIError:
    ...
```

2021-02-07 00:19 UTC, MarshalX commented on kks/ejudge_submit.py
> +        try:
А как это решает повторную отправку? Меня больше всего напрягал второй try внутри except. Если мы не хотим пробовать авторизоваться больше одного раза после ошибки, то писать какой-то цикл оверхед. Как и рекурсивную функцию

2021-02-07 00:28 UTC, vvd170501 commented on kks/ejudge_submit.py
> +        try:
Второй try отлавливал AuthError при попытке авторизации (например, если используется неверный логин/пароль).
Насчёт примера - плохо объяснил. `with_auth` - не цикл, а тот же самый try с авторизацией и повторным запросом при ошибке, только вынесенный в метод сессии.
Т.е. возможные варианты выполнения такие:
 - with_auth вызывает переданный метод API, ошибок не происходит или происходит ошибка, не связанная с авторизацией. Результат/ошибка возвращается
 - при запросе к API происходит ошибка авторизации (первый except). Выполняется `self.auth()` у объекта сессии
    - происходит ошибка авторизации (напр. неверный пароль) (второй except в старом варианте, with_auth не ловит её)
    - авторизация прошла успешно, делается второй запрос к API, результат/ошибка возвращается

2021-02-07 00:44 UTC, vvd170501 commented on kks/ejudge_submit.py
> +        try:
Добавил

2021-02-07 01:18 UTC, MarshalX commented on kks/util/ejudge.py
> +                raise
Это точно перекинет исключение?) чёт не встречал такого. Обычно raise e

2021-02-07 01:28 UTC, vvd170501 commented on kks/util/ejudge.py
> +                raise
Да, перекинет. Но здесь действительно можно использовать `raise e`

2021-02-07 09:03 UTC, MarshalX requested changes

2021-02-07 09:03 UTC, MarshalX commented on kks/util/ejudge.py
> +        self._sids = {'SID': None, 'EJSID': None}
Почему ты отказываешься переделать это в датакласс?

2021-02-07 10:41 UTC, vvd170501 commented on kks/util/ejudge.py
> +        self._sids = {'SID': None, 'EJSID': None}
1) Поддерживается только в python3.7+
2) Опять придётся конвертировать словарь в экземпляр класса и обратно, как это было с `AuthData` (хотя выглядеть будет лучше)

2021-02-07 11:19 UTC, MarshalX commented on kks/util/ejudge.py
> +        self._sids = {'SID': None, 'EJSID': None}
1. Окей, убираем «дата». Остаётся класс
2. ?)

2021-02-07 11:26 UTC, vvd170501 commented on kks/util/ejudge.py
> +        self._sids = {'SID': None, 'EJSID': None}
2 пункт: ec137a0c
До этого коммита использовался просто класс. Да, можно использовать класс с совпадающими именами атрибутов, но тогда придётся писать что-то типа своего `asdict`, чтобы конвертировать класс в словарь

2021-02-07 11:32 UTC, MarshalX commented on kks/util/ejudge.py
> +            if e.code != APIError.INVALID_SESSION:
Можно просто не использовать одно исключение для двух ошибок и сделать два... Отлавливать только второе, а первыое не обрабатывать. Вот и будет перекидываться

2021-02-07 11:40 UTC, vvd170501 commented on kks/util/ejudge.py
> +            if e.code != APIError.INVALID_SESSION:
В таком случае проверка кода просто перенесётся в `API._request`. Если в будущем где-то будут нужны другие коды ошибок, то их обработку тоже придётся добавлять в `_request` и создавать по классу на каждый используемый код ошибки (для однородности кода).
Выглядит хуже, чем просто проверка кода ошибки там, где он действительно на что-то влияет

2021-02-07 12:00 UTC, MarshalX approved these changes

2021-02-07 12:26 UTC, merged