Интеграция с SSH
DarkKeks/kks pull request #66
Opened 2021-02-07 16:56 UTC by vvd170501

2021-02-08 12:54 UTC, vvd170501 commented
Добавлена поддержка работы с ejudge через ssh + ejudge-fuse (для КР).

В данный момент поддерживаются команды `sync` (только синхронизация условий) и `submit`.

2021-02-08 15:04 UTC, MarshalX requested changes

2021-02-08 15:04 UTC, MarshalX commented on kks/ejudge.py
> +        soup = BeautifulSoup(html, 'html.parser')
слишком жоская операция шоб быть в конструкторе. вызывать из конструктора тоже такое не надо

2021-02-08 15:04 UTC, MarshalX commented on kks/util/ssh.py
> +        self.connect(hostname, username=login, password=password)
жоска для конструктора

2021-02-08 15:04 UTC, MarshalX commented on kks/util/ssh.py
> +        self._timeout = int(environ.get('KKS_SSH_TIMEOUT', 5))
передавай в аргах

2021-02-08 15:04 UTC, MarshalX commented on kks/util/ssh.py
> +        self._timeout = int(environ.get('KKS_SSH_TIMEOUT', 5))
а арги из конфига или чего-либо еще. из места где твой энв разбирается на переменные

2021-02-08 16:58 UTC, vvd170501 commented on kks/cmd/sync.py
> +        get_statement = lambda problem: ejudge_statement(problem.href, session)
Чем можно это заменить? Навешивать отдельные ифы на каждую часть кода, которая получает данные от ejudge - вряд ли хорошая идея.

2021-02-08 17:05 UTC, vvd170501 commented on kks/cmd/submit.py
> +    use_ssh = ssh_enabled()
При каждом вызове читается файл конфига (неоптимально). Попробую создать класс для нормальной работы с конфигом

2021-02-08 17:17 UTC, vvd170501 commented on kks/ejudge.py
> +        super().__init__(short_name, name)
В принципе, разницы нет. Исправлю

2021-02-08 17:20 UTC, vvd170501 commented on kks/ejudge.py
> +        soup = BeautifulSoup(html, 'html.parser')
Если импортировать на уровне модуля, то импорт будет происходить при запуске любой команды (`kks.ejudge` импортируется на уровне модулей команд, которые импортируются уже в `kks.cli`).
Это лишние 50-80 мс ожидания.

2021-02-08 17:23 UTC, vvd170501 commented on kks/ejudge.py
> +        soup = BeautifulSoup(html, 'html.parser')
Класс `WebStatement` используется только при синхронизации (которая в любом случае занимает много времени), поэтому задержка при создании первого экземпляра класса не так важна

2021-02-08 17:33 UTC, vvd170501 commented on kks/util/ssh.py
> +        self.connect(hostname, username=login, password=password)
Создаётся только один экземпляр объекта, причём установить подключение нужно один раз, сразу после создания. Если вызывать connect отдельно от создания объекта, то есть 2 варианта;
```
client = EjudgeSSHClient(mnt_dir, contest)
client.connect(hostname, login, password)
```
```
client = EjudgeSSHClient(hostname, login, password, mnt_dir, contest)
client.connect()  # переопределяем метод класса
```

Это выглядит хуже, чем просто создание объекта (connect все равно придётся заворачивать в try/except)

2021-02-08 17:48 UTC, vvd170501 commented on kks/util/ssh.py
> +        self._timeout = int(environ.get('KKS_SSH_TIMEOUT', 5))
Сливать переменые окружения в конфиг - как-то не очень (смешивать сохранённые учётные данные / ссылки с одноразовыми переменными, которые никак с ними не связаны).
Отдельный класс / функция для разбора переменных окружения (по сути, обёртка над get словаря) - выглядит не очень полезно.
Как вариант - можно просто вынести куда-нибудь значения переменных по умолчанию (что-то типа примера ниже)
```
class EnvDefaults:
    MDWIDTH = 100
    KKS_SSH_TIMEOUT = 5
```

2021-02-08 18:58 UTC, vvd170501 commented on kks/cmd/submit.py
> +    use_ssh = ssh_enabled()
Хотя да, здесь в любом случае можно было сразу в ифе вызывать (дальше не используется). Скопипастил из sync, где переменная ипользовалась в нескольких местах

2021-02-08 19:05 UTC, vvd170501 commented on kks/cmd/ssh.py
> +            login = login or ssh_cfg['login']
> а в default какую-нить функцию "умную" что твою секцию проверять будет и по ключу доставать

Либо нужно писать по функции для каждого имени ключа, либо всё-таки придётся использовать лямбды (ещё есть `default_map`, но он будет загружать конфиг даже для всех команд, которым он не нужен)

2021-02-08 19:36 UTC, vvd170501 commented on kks/cmd/ssh.py
> +            login = login or ssh_cfg['login']
Переписал. Проверять секцию оказалось не нужно, у `ConfigParser` есть параметр fallback

2021-02-08 20:35 UTC, vvd170501 commented on kks/cmd/ssh.py
> +            login = login or ssh_cfg['login']
default_map смотрел, он должен добавляться в cli, поэтому конфиг будет загружаться при запуске любой команды (а это как раз не нужно).
Насчёт синглтона - всё равно нужно было реализовать какой-то способ не перечитывать конфиг при каждом вызове `load_xxx` - секции Auth и Links (в EjudgeSession), SSH и Auth (в cmd.ssh) читаются вместе

2021-02-08 21:00 UTC, vvd170501 commented on kks/ejudge.py
> +        soup = BeautifulSoup(html, 'html.parser')
> вызывать из конструктора тоже такое не надо

Если это относится не к импортам, а к парсингу html при инициализации - альтернатива, вроде, только одна - хранить полный код страницы в объекте, а парсить его в отдельном методе. 
Результат парсинга используется сразу же после создания объекта, поэтому не вижу смысла выносить его в отдельный метод.

2021-02-08 21:24 UTC, MarshalX commented on kks/util/ssh.py
> +        self.connect(hostname, username=login, password=password)
Во-первых второй сниппет секс. Во-вторых 

> Создаётся только один экземпляр объекта, причём установить подключение нужно один раз

Хардкодное программирование? Что значит один экземпляр объекта. Синглтон не так реализуется в питоне. У тебя обычный нормальный класс и я ожидаю плодить сколько хочу объектов, а не потому что кто-то заложил логику, что 1 класс == 1 объект и сообщил об этом в комменте в ПРе.

Если так сильно хочется в одном методе юзать, ну сделай классовый метод, ты же часто их применяешь. Назови его "создать и подключиться". Там бахай свой экземляр и вызывай сразу .connect хоть под try, хоть под чем)0

2021-02-08 21:26 UTC, MarshalX commented on kks/ejudge.py
> +        soup = BeautifulSoup(html, 'html.parser')
парсить слишком жоска. Про "вызывать из конструктора" я говорил чтоб ты не дай бог сделал парс в методе, но этот метод вызвал в конструкторе. То есть сменил шило на мыло

2021-02-08 21:28 UTC, MarshalX commented on kks/util/ssh.py
> +        self._timeout = int(environ.get('KKS_SSH_TIMEOUT', 5))
Фиг знает чо какой тут конфиг в проекте, но вот тебе [HOCON](https://github.com/chimpler/pyhocon). Он умеет из энва подставлять переменки и они как часть всего конфига

2021-02-08 21:30 UTC, vvd170501 commented on kks/util/ssh.py
> +        self.connect(hostname, username=login, password=password)
Про один экземпляр - это не о том, что не предполагается существование других экземпляроа. Имелось в виду, что объект создаётся только там, где действительно нужен, и поэтому время инициализации не так важно.

Насчёт классового метода - да, так можно сделать

2021-02-08 21:51 UTC, vvd170501 commented on kks/ejudge.py
> +        soup = BeautifulSoup(html, 'html.parser')
Конкретно для этого класса не вижу смысла что-то менять. Все равно в него передаётся html-код полной страницы, который сам по себе (без парсинга) не нужен.

2021-02-08 22:45 UTC, vvd170501 commented on kks/util/ssh.py
> +        self._timeout = int(environ.get('KKS_SSH_TIMEOUT', 5))
Хранить дефолтные значения отдельно от кода имеет смысл, если есть способ их изменять (см. `kks.util.config` (это не тот конфиг) и `targets.yaml`).

Файл конфигурации (`config.ini`) _можно_ редактировать вручную, но такая возможность не документирована (предполагается, что он создаётся / изменяется с помощью команд `kks auth` и `kks ssh`). По сути, это такой же внутренний файл для хранения данных, как `cookies.pickle` и другие.

2021-02-08 23:37 UTC, vvd170501 commented on kks/cmd/submit.py
> +        result = submit_solution_ssh(client, file, problem, timeout or ssh_testing_timeout)
Переписал получение таймаута

2021-02-08 23:48 UTC, vvd170501 commented on kks/cmd/submit.py
> +        result = submit_solution_ssh(client, file, problem, timeout or ssh_testing_timeout)
Переписал вызовы функций в e7653a7 (`connections` используется, т.к. в будущем может возникнуть необходимость использовать сессию в `ejudge_submit_ssh`, см. комментарий в #60 )

2021-02-09 00:43 UTC, vvd170501 commented on kks/cmd/sync.py
> +        get_statement = lambda problem: ejudge_statement(problem.href, session)
Правильным (наверное) решением было бы перенести код для работы с сессией / апи из методов `kks.ejudge.ejudge_xxx` в класс `EjudgeHTTPClient`, у которого сигнатуры методов совпадают с `EjudgeSSHClient`, а в `ejudge_xxx` оставить только обработку результатов (примерно так сейчас реализован `ejudge_submit`).

Реализовывать такой вариант в этой ветке не стоит, т.к. в таком случае будет слишком много изменений и увеличится шанс что-нибудь сломать

2021-02-09 05:06 UTC, DarkKeks commented on kks/cmd/ssh.py
> +            login = login or ssh_cfg['login']
Речь как раз о том, что конфиг не должен быть "глобальным"
Тогда проще следить за количеством чтений, потому что ты читаешь один раз объект, а потом передаешь везде где надо как зависимость

То есть `EjudgeSession` не должно само ходить в конфиг. Конфиг должен использоваться при создании сессии как зависимость, например в статическом методе, или в утильном
Или сделать отдельный класс "фабрику сессий", если логика начинает становиться слишком сложной

Сейчас же получается что `EjudgeSession` это вроде объект с парой sid+ejsid, но при этом зачем-то еще умеет ходить в конфиг, при том что исопльзуется это только при авторизации (== создании)

2021-02-09 05:23 UTC, DarkKeks commented on kks/util/ssh.py
> +        self._timeout = int(environ.get('KKS_SSH_TIMEOUT', 5))
Конфиг не предполагался к редактированию вручную, потому что не было повода

Если ты добавляешь какие то параметры, от изменения которых руками есть польза, не вижу проблемы в том чтобы изменять их только из конфига, либо отдельной командой для модификации конфига

Конфиг мы как раз показываем как "публичное апи" для пользователей, в отличии от индекса контестов/etc &mdash; он упоминается в README и описаниях команд

"Задать переменную окружения" и "поменять строку в конфиге" &mdash; одинаково стремные для пользователя действия. В любом случае ему придется о них узнать, например, из описания команды

---
Насчет переменной окружения
Лично я бы предпочел чтобы это значение задавалось конфигом, потмоу что если его пришлось менять, то скорее всего придется менять каждый раз

И если уже делать полноценный конфиг, то замену значения на env/дефолт стоит унести туда в каком-либо виде. В создании клиента ей не место

2021-02-09 08:16 UTC, vvd170501 commented on kks/cmd/ssh.py
> +            login = login or ssh_cfg['login']
> при том что исопльзуется это только при авторизации

В него пишутся новые ссылки при обновлении куков (возможно, стоит перенести их оттуда в другой файл или вообще хранить только sid - имена разделов не менялись с 2013 года (blackav/ejudge@41802c97d8f99d38d2b0c069d184e5a2ef372238)

> Конфиг должен использоваться при создании сессии как зависимость

Проблемы с использованием отдельных объектов конфига (которые используют один и тот же файл):
- Если случайно создать два объекта (в чём смысл намеренно это делать?), то могут возникнуть проблемы с чтением/записью - 2 объекта изменяют какие-то данные, сохраняется на диск только одна из версий. Решения - читать конфиг заново перед каждым изменением (плохо) или сделать конфиг ридонли (хардкодить базовые ссылки ссылки и хранить sid в `cookies.pickle` / где-то еще)
- Для сессии (в реализации, используемой сейчас) нужна возможность обновления конфига, значит, придётся его хранить как атрибут сессии - опять получается, что у сессии есть постоянный доступ к конфигу.
- Придётся реализовывать какую-то сложную логику для чтения дефолтных аргументов `kks ssh` - использовать какой-то декоратор для загрузки конфига, и как-то передавать его во все коллбеки для дефолтных значений

2021-02-09 08:23 UTC, vvd170501 commented on kks/cmd/ssh.py
> +            login = login or ssh_cfg['login']
> Тогда проще следить за количеством чтений, потому что ты читаешь один раз объект

Вроде, если добавить явную возможность создать несколько объектов (при создании каждого из которых происходит чтение), следить за их количеством становится сложнее.
В варианте с синглтоном гарантируется, что чтение будет произведено максимум один раз.
В таком случае тоже могут возникнуть проблемы из-за общего доступа к изменяемому конфигу, но это уже проблемы на уровне "запись/чтение из одного словаря", а не возможность рассинхронизации объекта с файлом конфига, хранящимся на диске

2021-02-09 09:12 UTC, vvd170501 commented on kks/util/ssh.py
> +        self._timeout = int(environ.get('KKS_SSH_TIMEOUT', 5))
> Конфиг мы как раз показываем как "публичное апи" для пользователей, в отличии от индекса контестов/etc — он упоминается в README и описаниях команд

Из того, что _сейчас_ есть в README - только упоминание о хранении пароля в plaintext, про возможность настройки через `config.ini` ничего не говорится. Все остальные упоминания конфига (`kks config`) относятся к таргетам (возможно, стоило назвать команду по-другому)

> если [значение переменной окружения] пришлось менять, то скорее всего придется менять каждый раз

Для таймаута (в общем случае) нет смысла изменять дефолтное значение. Он используется в случае, если ssh-сервер начинает лагать (было на первой КР,, на второй проблем не было), причём должна быть возможность изменять параметр без запуска отдельной команды / редактирования файла (например, увеличение таймаута не помогло и нужно поставить ещё большее значение).
Почему используется именно переменная окружения, а не аргумент - (1) у `kks sync` уже есть аргумент таймаута с другим смыслом; (2) может использоваться не в одной команде

Насчёт `MDWIDTH` - да, скорее всего, значение придётся изменять постоянно. Его _можно_ перенести в конфиг, но тогда возникают следующие проблемы:
1)  если хранить дефолтное значение в конфиге и давать возможность его переопределять через переменную окружения, то код конфига будет слишком сложным / неочевидным. Сейчас конфиг поддерживает обновление / запись данных, поэтому нельзя просто смержить в него переменные окружения в него (при записи испортятся дефолтные значения). Решение - вынос ссылок из конфига и доступ только на чтение.
2)  если хранить _только_ значение в конфиге (вряд ли понадобится его часто менять, поэтому переменная окружения в принципе не нужна), то:
     - новая версия (в какой-то степени) сломает обратную совместимость - если у пользователя было переопределено дефолтное значение переменной, оно теперь не будет учитываться
     - для таймаута все равно нужно оставить возможность быстрого переопределения (см. выше). Придётся или мержить его в конфиг (см. п. 1), или оставить его как есть (переопределение _только_ через переменную). Во втором случае получаетсяя слишком много различных способов изменять настройки - переменные окружения / аргументы запуска / редактирование конфига (сейчас это _недокументированный_ способ)

2021-02-09 09:56 UTC, vvd170501 commented on kks/util/ssh.py
> +        self._timeout = int(environ.get('KKS_SSH_TIMEOUT', 5))
В любом случае, если изменять формат настроек или способы их изменения, то это стоит делать в отдельном ПР или вообще выпускать новую мажорную версию

2021-02-10 15:40 UTC, vvd170501 commented on kks/cmd/sync.py
> +        get_statement = lambda problem: ejudge_statement(problem.href, session)
Заменил лямбды на отдельный иф. Пока не вижу лучшего варианта, который можно реализовать прямо сейчас.

2021-02-11 09:46 UTC, DarkKeks commented on kks/cmd/ssh.py
> +@click.option('-hn', '--hostname', default=get_hostname)
Не стоит юзать двубуквенные сокращения
Это ломает возможность писать много флагов за раз, например `kks top -gam`
Да и зачем сокращение, если оно "длинное")
Лучше сделать какую нибудь левую букву
В данном случае вообще -h/-H не занято

2021-02-11 10:57 UTC, vvd170501 commented on kks/cmd/ssh.py
> +@click.option('-hn', '--hostname', default=get_hostname)
Ок, переделаю

2021-02-11 11:04 UTC, vvd170501 commented
Переношу в #70, #71, т.к. изменение работы с конфигом лучше сделать отдельно

2021-02-11 11:04 UTC, closed without merging